# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- pod install --project-directory=Example
- brew upgrade xctool || true
script:
- pod lib lint
- xctool -workspace Example/NotificationManager.xcworkspace -scheme 'NotificationManager-Example' -sdk iphonesimulator -arch i386 test
